# Generated by Django 2.1.7 on 2020-05-28 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='public_key_id',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
