# Generated by Django 2.2 on 2020-05-28 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_user_public_key_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key_id', models.CharField(blank=True, max_length=32, null=True)),
                ('public_key', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
