# Generated by Django 2.2 on 2020-05-28 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_publickey_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='publickey',
            name='e',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publickey',
            name='n',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
