# Generated by Django 2.2 on 2020-05-28 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_auto_20200528_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publickey',
            name='n',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='publickey',
            name='public_key',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
