# Generated by Django 2.2 on 2020-05-28 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_auto_20200528_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publickey',
            name='n',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='publickey',
            name='public_key',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
