# Generated by Django 2.2 on 2020-05-29 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_auto_20200528_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='publickey',
            name='algorithm',
            field=models.CharField(default='rsa-sha256', max_length=32),
        ),
        migrations.AlterField(
            model_name='publickey',
            name='e',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
