# Generated by Django 2.2 on 2020-06-10 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_auto_20200609_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='app_secret_token',
            field=models.CharField(blank=True, max_length=65, null=True),
        ),
        migrations.AlterField(
            model_name='publickey',
            name='public_key',
            field=models.TextField(default=1234, max_length=500),
            preserve_default=False,
        ),
    ]
