# Generated by Django 2.2 on 2020-06-10 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_auto_20200610_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresettoken',
            name='expires_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
