# Generated by Django 2.2 on 2020-06-10 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0014_passwordresettoken_expires_on'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PasswordResetToken',
            new_name='PasswordResetRequest',
        ),
    ]
