# Generated by Django 2.2 on 2020-06-10 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0015_auto_20200610_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_app_secret_seen',
            field=models.BooleanField(default=False),
        ),
    ]
