# Generated by Django 2.2.13 on 2020-09-17 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0018_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresetrequest',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
    ]
