# Generated by Django 2.1.7 on 2020-05-12 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vpnclientevent',
            name='new_android_log',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vpnclientevent',
            name='previous_android_log',
            field=models.TextField(blank=True, null=True),
        ),
    ]
