# Generated by Django 2.1.7 on 2020-05-14 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0002_auto_20200512_1751'),
    ]

    operations = [
        migrations.CreateModel(
            name='CjdnsVpnNetworkSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uses_nat', models.BooleanField(default=True)),
                ('per_client_allocation_size', models.CharField(default='/0', max_length=32)),
            ],
            options={
                'verbose_name_plural': 'Cjdns Vpn Network Settings',
            },
        ),
        migrations.CreateModel(
            name='CjdnsVpnServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('public_key', models.CharField(max_length=64)),
                ('bandwidth_bps', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('online_since_datetime', models.DateTimeField(auto_now_add=True)),
                ('last_seen_datetime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CjdnsVpnServerPeeringLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('login', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=64)),
                ('cjdns_vpn_server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vpn.CjdnsVpnServer')),
            ],
        ),
        migrations.CreateModel(
            name='ClientSoftwareVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_os', models.CharField(blank=True, choices=[('Android', 'android'), ('iOS', 'ios'), ('Mac OS', 'macos'), ('Windows', 'windows'), ('Linux', 'linux')], max_length=20)),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('slug', models.SlugField(blank=True, max_length=64, null=True)),
                ('major_number', models.PositiveSmallIntegerField()),
                ('minor_number', models.PositiveSmallIntegerField()),
                ('revision_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('binary_download_url', models.URLField(max_length=300)),
                ('certificate_url', models.URLField(max_length=300)),
                ('release_datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NetworkExitRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min', models.CharField(max_length=64)),
                ('max', models.CharField(max_length=64)),
                ('cjdns_vpn_network_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vpn.CjdnsVpnNetworkSettings')),
            ],
        ),
        migrations.AddField(
            model_name='cjdnsvpnnetworksettings',
            name='cjdns_vpn_server',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vpn.CjdnsVpnServer'),
        ),
    ]
