# Generated by Django 2.1.7 on 2020-05-15 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0003_auto_20200514_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cjdnsvpnserver',
            name='bandwidth_bps',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientsoftwareversion',
            name='client_os',
            field=models.CharField(blank=True, choices=[('android', 'Android'), ('ios', 'iOS'), ('macos', 'Mac OS'), ('windows', 'Windows'), ('linux', 'Linux')], max_length=20),
        ),
    ]
