# Generated by Django 2.1.7 on 2020-05-15 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0004_auto_20200515_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkexitrange',
            name='type',
            field=models.CharField(choices=[('exit', 'Exit Range'), ('client_allocation', 'Allocation Range')], default='exit', max_length=32),
            preserve_default=False,
        ),
    ]
