# Generated by Django 2.1.7 on 2020-05-15 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0005_networkexitrange_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='vpnclientevent',
            name='available_memory',
            field=models.CharField(default='1024', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vpnclientevent',
            name='cpu_utilization',
            field=models.CharField(default=97, max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='networkexitrange',
            name='type',
            field=models.CharField(choices=[('nat_exit', 'Exit Range'), ('client_allocation', 'Allocation Range')], max_length=32),
        ),
    ]
