# Generated by Django 2.1.7 on 2020-05-21 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0008_auto_20200518_0803'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsoftwareversion',
            name='client_cpu_architecture',
            field=models.CharField(blank=True, choices=[('i686', 'i686'), ('aarch64', 'aarch64'), ('armv7a', 'armv7a'), ('X86_64', 'X86_64')], max_length=20),
        ),
        migrations.AlterField(
            model_name='vpnclientevent',
            name='error',
            field=models.CharField(choices=[('connection_failed', 'Could not connect'), ('disconnection', 'Unexpected disconnection'), ('route_stopped', 'Connected but unable to route traffic'), ('cjdns_crash', 'CJDNS crashed'), ('connection', 'VPN client connected'), ('disconnection', 'VPN client disconnected'), ('cjdroute', 'Cjdroute problem'), ('cjdns_socket', 'Cjdns socket error'), ('vpn_service', 'VPN service problem'), ('other', 'Other reason')], max_length=64),
        ),
        migrations.AlterField(
            model_name='vpnclientevent',
            name='public_key',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
