# Generated by Django 2.1.7 on 2020-05-22 14:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0010_auto_20200522_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cjdnsvpnserver',
            name='bandwidth_bps',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
