# Generated by Django 2.1.7 on 2020-05-25 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0012_auto_20200525_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vpnclientevent',
            name='error',
            field=models.CharField(choices=[('connectionFailed', 'Could not connect'), ('disconnection', 'Unexpected disconnection'), ('routeStopped', 'Connected but unable to route traffic'), ('cjdnsCrash', 'CJDNS crashed'), ('connection', 'VPN client connected'), ('disconnection', 'VPN client disconnected'), ('cjdroute', 'Cjdroute problem'), ('cjdnsSocket', 'Cjdns socket error'), ('vpnService', 'VPN service problem'), ('other', 'Other reason'), ('routeStopped', 'Connected but unable to route traffic'), ('cjdnsCrash', 'CJDNS crashed'), ('vpnService', 'VPN service problem')], max_length=64),
        ),
    ]
