# Generated by Django 2.2 on 2020-06-12 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0014_auto_20200525_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='cjdnsvpnserver',
            name='authorization_server_url',
            field=models.CharField(default='http://127.0.0.1:5335', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cjdnsvpnserver',
            name='cjdns_public_ip',
            field=models.CharField(default='127.0.0.1', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cjdnsvpnserver',
            name='cjdns_public_port',
            field=models.PositiveSmallIntegerField(default=6332),
        ),
    ]
