# Generated by Django 2.2 on 2020-06-12 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0015_auto_20200612_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='cjdnsvpnserver',
            name='slug',
            field=models.CharField(default='aesnuhaosunth', max_length=64),
            preserve_default=False,
        ),
    ]
