# Generated by Django 2.2 on 2020-06-12 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0016_cjdnsvpnserver_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cjdnsvpnserver',
            name='slug',
        ),
    ]
