# Generated by Django 2.2 on 2020-06-26 11:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0017_remove_cjdnsvpnserver_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsoftwareversion',
            name='file_size_bytes',
            field=models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
