# Generated by Django 2.2 on 2020-07-14 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0018_clientsoftwareversion_file_size_bytes'),
    ]

    operations = [
        migrations.AddField(
            model_name='vpnclientevent',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vpnclientevent',
            name='error',
            field=models.CharField(max_length=64),
        ),
    ]
