# Generated by Django 2.2.13 on 2020-10-09 19:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0021_auto_20201009_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='cjdnsvpnserver',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cjdnsvpnserver',
            name='last_seen_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
