# Generated by Django 2.2.13 on 2021-01-10 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0023_usercjdnsvpnserverrating_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='cjdnsvpnserver',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='cjdnsvpnserver',
            name='load',
            field=models.PositiveSmallIntegerField(default=52),
        ),
        migrations.AddField(
            model_name='cjdnsvpnserver',
            name='quality',
            field=models.PositiveSmallIntegerField(default=2),
        ),
    ]
