# Generated by Django 2.1.7 on 2020-04-29 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VpnClientEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key', models.CharField(max_length=64)),
                ('error', models.CharField(choices=[('connection_failed', 'Could not connect'), ('disconnection', 'Unexpected disconnection'), ('route_stopped', 'Connected but unable to route traffic'), ('cjdns_crash', 'CJDNS crashed'), ('connection', 'VPN client connected'), ('disconnection', 'VPN client disconnected'), ('other', 'Other reason')], max_length=64)),
                ('client_software_version', models.CharField(max_length=32)),
                ('client_os', models.CharField(max_length=32)),
                ('client_os_version', models.CharField(max_length=32)),
                ('local_timestamp', models.DateTimeField()),
                ('ip4_address', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4')),
                ('ip6_address', models.GenericIPAddressField(blank=True, null=True, protocol='IPv6')),
                ('message', models.CharField(max_length=100)),
                ('debugging_messages', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
